head_pred(transport,1).
body_pred(position_joint_1_constant,1).
body_pred(position_joint_1_ramp_up,1).
body_pred(position_joint_1_ramp_down,1).
body_pred(position_joint_2_constant,1).
body_pred(position_joint_2_ramp_up,1).
body_pred(position_joint_2_ramp_down,1).
body_pred(position_joint_3_constant,1).
body_pred(position_joint_3_ramp_up,1).
body_pred(position_joint_3_ramp_down,1).
body_pred(position_joint_4_constant,1).
body_pred(position_joint_4_ramp_up,1).
body_pred(position_joint_4_ramp_down,1).
body_pred(position_joint_5_constant,1).
body_pred(position_joint_5_ramp_up,1).
body_pred(position_joint_5_ramp_down,1).
body_pred(position_joint_6_constant,1).
body_pred(position_joint_6_ramp_up,1).
body_pred(position_joint_6_ramp_down,1).
body_pred(position_joint_7_constant,1).
body_pred(position_joint_7_ramp_up,1).
body_pred(position_joint_7_ramp_down,1).
body_pred(position_finger_1_constant,1).
body_pred(position_finger_1_ramp_up,1).
body_pred(position_finger_1_ramp_down,1).
body_pred(position_finger_2_constant,1).
body_pred(position_finger_2_ramp_up,1).
body_pred(position_finger_2_ramp_down,1).
max_vars(1).
max_body(3).
max_clauses(3).
