% Positive examples = place transitions
% Negative examples = non-place transitions

pos(phase_place(s94)).
pos(phase_place(s95)).
pos(phase_place(s96)).
pos(phase_place(s97)).
pos(phase_place(s98)).
pos(phase_place(s99)).
pos(phase_place(s100)).
pos(phase_place(s101)).
pos(phase_place(s102)).
pos(phase_place(s103)).

neg(phase_place(s0)).
neg(phase_place(s1)).
neg(phase_place(s2)).
neg(phase_place(s3)).
neg(phase_place(s4)).
neg(phase_place(s6)).
neg(phase_place(s7)).
neg(phase_place(s8)).
neg(phase_place(s9)).
neg(phase_place(s10)).
neg(phase_place(s11)).
neg(phase_place(s12)).
neg(phase_place(s13)).
neg(phase_place(s14)).
neg(phase_place(s15)).
neg(phase_place(s16)).
neg(phase_place(s17)).
neg(phase_place(s18)).
neg(phase_place(s19)).
neg(phase_place(s20)).
neg(phase_place(s21)).
neg(phase_place(s23)).
neg(phase_place(s24)).
neg(phase_place(s25)).
neg(phase_place(s26)).
neg(phase_place(s27)).
neg(phase_place(s28)).
neg(phase_place(s29)).
neg(phase_place(s30)).
neg(phase_place(s31)).
neg(phase_place(s32)).
neg(phase_place(s33)).
neg(phase_place(s34)).
neg(phase_place(s35)).
neg(phase_place(s36)).
neg(phase_place(s37)).
neg(phase_place(s38)).
neg(phase_place(s39)).
neg(phase_place(s40)).
neg(phase_place(s41)).
neg(phase_place(s42)).
neg(phase_place(s43)).
neg(phase_place(s44)).
neg(phase_place(s45)).
neg(phase_place(s46)).
neg(phase_place(s47)).
neg(phase_place(s48)).
neg(phase_place(s49)).
neg(phase_place(s50)).
neg(phase_place(s51)).
neg(phase_place(s52)).
neg(phase_place(s53)).
neg(phase_place(s54)).
neg(phase_place(s56)).
neg(phase_place(s57)).
neg(phase_place(s58)).
neg(phase_place(s59)).
neg(phase_place(s60)).
neg(phase_place(s61)).
neg(phase_place(s62)).
neg(phase_place(s63)).
neg(phase_place(s64)).
neg(phase_place(s65)).
neg(phase_place(s66)).
neg(phase_place(s67)).
neg(phase_place(s68)).
neg(phase_place(s69)).
neg(phase_place(s71)).
neg(phase_place(s72)).
neg(phase_place(s73)).
neg(phase_place(s74)).
neg(phase_place(s75)).
neg(phase_place(s76)).
neg(phase_place(s77)).
neg(phase_place(s78)).
neg(phase_place(s80)).
neg(phase_place(s81)).
neg(phase_place(s82)).
neg(phase_place(s83)).
neg(phase_place(s84)).
neg(phase_place(s85)).
neg(phase_place(s86)).
neg(phase_place(s87)).
neg(phase_place(s88)).
neg(phase_place(s89)).
neg(phase_place(s90)).
neg(phase_place(s91)).
neg(phase_place(s92)).
neg(phase_place(s105)).
neg(phase_place(s106)).
neg(phase_place(s107)).
neg(phase_place(s108)).
neg(phase_place(s109)).
neg(phase_place(s110)).
neg(phase_place(s111)).
neg(phase_place(s112)).
neg(phase_place(s113)).
neg(phase_place(s115)).
neg(phase_place(s116)).
neg(phase_place(s117)).
neg(phase_place(s118)).
neg(phase_place(s119)).
neg(phase_place(s120)).
neg(phase_place(s121)).
neg(phase_place(s122)).
neg(phase_place(s123)).
neg(phase_place(s124)).
neg(phase_place(s125)).
neg(phase_place(s126)).
neg(phase_place(s128)).
neg(phase_place(s129)).
neg(phase_place(s130)).
neg(phase_place(s131)).
neg(phase_place(s132)).
neg(phase_place(s133)).
neg(phase_place(s134)).
neg(phase_place(s135)).
neg(phase_place(s136)).
neg(phase_place(s137)).
neg(phase_place(s138)).
neg(phase_place(s139)).
neg(phase_place(s140)).
neg(phase_place(s141)).
neg(phase_place(s142)).
neg(phase_place(s143)).
neg(phase_place(s144)).
neg(phase_place(s145)).
neg(phase_place(s146)).
neg(phase_place(s147)).
neg(phase_place(s148)).
neg(phase_place(s149)).
neg(phase_place(s150)).
neg(phase_place(s151)).
neg(phase_place(s152)).
neg(phase_place(s153)).
neg(phase_place(s154)).
neg(phase_place(s155)).
