head_pred(phase_retract,1).
max_vars(1).
max_body(5).
max_clauses(3).
type(phase_retract,(example,)).
direction(phase_retract,(in,)).
body_pred(j1_constant,1).
type(j1_constant,(example,)).
direction(j1_constant,(in,)).
body_pred(j1_ramp_down,1).
type(j1_ramp_down,(example,)).
direction(j1_ramp_down,(in,)).
body_pred(j1_ramp_up,1).
type(j1_ramp_up,(example,)).
direction(j1_ramp_up,(in,)).
body_pred(j2_constant,1).
type(j2_constant,(example,)).
direction(j2_constant,(in,)).
body_pred(j2_ramp_down,1).
type(j2_ramp_down,(example,)).
direction(j2_ramp_down,(in,)).
body_pred(j2_ramp_up,1).
type(j2_ramp_up,(example,)).
direction(j2_ramp_up,(in,)).
body_pred(j3_constant,1).
type(j3_constant,(example,)).
direction(j3_constant,(in,)).
body_pred(j3_ramp_down,1).
type(j3_ramp_down,(example,)).
direction(j3_ramp_down,(in,)).
body_pred(j3_ramp_up,1).
type(j3_ramp_up,(example,)).
direction(j3_ramp_up,(in,)).
body_pred(j4_constant,1).
type(j4_constant,(example,)).
direction(j4_constant,(in,)).
body_pred(j4_ramp_down,1).
type(j4_ramp_down,(example,)).
direction(j4_ramp_down,(in,)).
body_pred(j5_constant,1).
type(j5_constant,(example,)).
direction(j5_constant,(in,)).
body_pred(j5_ramp_down,1).
type(j5_ramp_down,(example,)).
direction(j5_ramp_down,(in,)).
body_pred(j5_ramp_up,1).
type(j5_ramp_up,(example,)).
direction(j5_ramp_up,(in,)).
