% Velocity-only bias: no position and no effort predicates.
max_vars(1).
max_body(4).
max_clauses(3).

head_pred(phase_gripper_opening,1).
body_pred(j1_vel_increases,1).
body_pred(j1_vel_decreases,1).
body_pred(j1_vel_constant,1).
body_pred(j2_vel_increases,1).
body_pred(j2_vel_decreases,1).
body_pred(j2_vel_constant,1).
body_pred(j3_vel_increases,1).
body_pred(j3_vel_decreases,1).
body_pred(j3_vel_constant,1).
body_pred(j4_vel_increases,1).
body_pred(j4_vel_decreases,1).
body_pred(j4_vel_constant,1).
body_pred(j5_vel_increases,1).
body_pred(j5_vel_decreases,1).
body_pred(j5_vel_constant,1).
body_pred(j6_vel_increases,1).
body_pred(j6_vel_decreases,1).
body_pred(j6_vel_constant,1).

type(phase_gripper_opening,(state,)).
type(j1_vel_increases,(state,)).
type(j1_vel_decreases,(state,)).
type(j1_vel_constant,(state,)).
type(j2_vel_increases,(state,)).
type(j2_vel_decreases,(state,)).
type(j2_vel_constant,(state,)).
type(j3_vel_increases,(state,)).
type(j3_vel_decreases,(state,)).
type(j3_vel_constant,(state,)).
type(j4_vel_increases,(state,)).
type(j4_vel_decreases,(state,)).
type(j4_vel_constant,(state,)).
type(j5_vel_increases,(state,)).
type(j5_vel_decreases,(state,)).
type(j5_vel_constant,(state,)).
type(j6_vel_increases,(state,)).
type(j6_vel_decreases,(state,)).
type(j6_vel_constant,(state,)).

direction(phase_gripper_opening,(in,)).
direction(j1_vel_increases,(in,)).
direction(j1_vel_decreases,(in,)).
direction(j1_vel_constant,(in,)).
direction(j2_vel_increases,(in,)).
direction(j2_vel_decreases,(in,)).
direction(j2_vel_constant,(in,)).
direction(j3_vel_increases,(in,)).
direction(j3_vel_decreases,(in,)).
direction(j3_vel_constant,(in,)).
direction(j4_vel_increases,(in,)).
direction(j4_vel_decreases,(in,)).
direction(j4_vel_constant,(in,)).
direction(j5_vel_increases,(in,)).
direction(j5_vel_decreases,(in,)).
direction(j5_vel_constant,(in,)).
direction(j6_vel_increases,(in,)).
direction(j6_vel_decreases,(in,)).
direction(j6_vel_constant,(in,)).
