% Positive examples = gripper_opening
% Negative examples = non-gripper_opening

pos(phase_gripper_opening(s6)).
pos(phase_gripper_opening(s7)).
pos(phase_gripper_opening(s8)).
pos(phase_gripper_opening(s9)).
pos(phase_gripper_opening(s10)).
pos(phase_gripper_opening(s11)).
pos(phase_gripper_opening(s12)).
pos(phase_gripper_opening(s13)).
pos(phase_gripper_opening(s14)).
pos(phase_gripper_opening(s15)).
pos(phase_gripper_opening(s16)).
pos(phase_gripper_opening(s17)).
pos(phase_gripper_opening(s18)).
pos(phase_gripper_opening(s19)).
pos(phase_gripper_opening(s20)).
pos(phase_gripper_opening(s21)).
pos(phase_gripper_opening(s105)).
pos(phase_gripper_opening(s106)).
pos(phase_gripper_opening(s107)).
pos(phase_gripper_opening(s108)).
pos(phase_gripper_opening(s109)).
pos(phase_gripper_opening(s110)).
pos(phase_gripper_opening(s111)).
pos(phase_gripper_opening(s112)).
pos(phase_gripper_opening(s113)).

neg(phase_gripper_opening(s0)).
neg(phase_gripper_opening(s1)).
neg(phase_gripper_opening(s2)).
neg(phase_gripper_opening(s3)).
neg(phase_gripper_opening(s4)).
neg(phase_gripper_opening(s23)).
neg(phase_gripper_opening(s24)).
neg(phase_gripper_opening(s25)).
neg(phase_gripper_opening(s26)).
neg(phase_gripper_opening(s27)).
neg(phase_gripper_opening(s28)).
neg(phase_gripper_opening(s29)).
neg(phase_gripper_opening(s30)).
neg(phase_gripper_opening(s31)).
neg(phase_gripper_opening(s32)).
neg(phase_gripper_opening(s33)).
neg(phase_gripper_opening(s34)).
neg(phase_gripper_opening(s35)).
neg(phase_gripper_opening(s36)).
neg(phase_gripper_opening(s37)).
neg(phase_gripper_opening(s38)).
neg(phase_gripper_opening(s39)).
neg(phase_gripper_opening(s40)).
neg(phase_gripper_opening(s41)).
neg(phase_gripper_opening(s42)).
neg(phase_gripper_opening(s43)).
neg(phase_gripper_opening(s44)).
neg(phase_gripper_opening(s45)).
neg(phase_gripper_opening(s46)).
neg(phase_gripper_opening(s47)).
neg(phase_gripper_opening(s48)).
neg(phase_gripper_opening(s49)).
neg(phase_gripper_opening(s50)).
neg(phase_gripper_opening(s51)).
neg(phase_gripper_opening(s52)).
neg(phase_gripper_opening(s53)).
neg(phase_gripper_opening(s54)).
neg(phase_gripper_opening(s56)).
neg(phase_gripper_opening(s57)).
neg(phase_gripper_opening(s58)).
neg(phase_gripper_opening(s59)).
neg(phase_gripper_opening(s60)).
neg(phase_gripper_opening(s61)).
neg(phase_gripper_opening(s62)).
neg(phase_gripper_opening(s63)).
neg(phase_gripper_opening(s64)).
neg(phase_gripper_opening(s65)).
neg(phase_gripper_opening(s66)).
neg(phase_gripper_opening(s67)).
neg(phase_gripper_opening(s68)).
neg(phase_gripper_opening(s69)).
neg(phase_gripper_opening(s71)).
neg(phase_gripper_opening(s72)).
neg(phase_gripper_opening(s73)).
neg(phase_gripper_opening(s74)).
neg(phase_gripper_opening(s75)).
neg(phase_gripper_opening(s76)).
neg(phase_gripper_opening(s77)).
neg(phase_gripper_opening(s78)).
neg(phase_gripper_opening(s80)).
neg(phase_gripper_opening(s81)).
neg(phase_gripper_opening(s82)).
neg(phase_gripper_opening(s83)).
neg(phase_gripper_opening(s84)).
neg(phase_gripper_opening(s85)).
neg(phase_gripper_opening(s86)).
neg(phase_gripper_opening(s87)).
neg(phase_gripper_opening(s88)).
neg(phase_gripper_opening(s89)).
neg(phase_gripper_opening(s90)).
neg(phase_gripper_opening(s91)).
neg(phase_gripper_opening(s92)).
neg(phase_gripper_opening(s94)).
neg(phase_gripper_opening(s95)).
neg(phase_gripper_opening(s96)).
neg(phase_gripper_opening(s97)).
neg(phase_gripper_opening(s98)).
neg(phase_gripper_opening(s99)).
neg(phase_gripper_opening(s100)).
neg(phase_gripper_opening(s101)).
neg(phase_gripper_opening(s102)).
neg(phase_gripper_opening(s103)).
neg(phase_gripper_opening(s115)).
neg(phase_gripper_opening(s116)).
neg(phase_gripper_opening(s117)).
neg(phase_gripper_opening(s118)).
neg(phase_gripper_opening(s119)).
neg(phase_gripper_opening(s120)).
neg(phase_gripper_opening(s121)).
neg(phase_gripper_opening(s122)).
neg(phase_gripper_opening(s123)).
neg(phase_gripper_opening(s124)).
neg(phase_gripper_opening(s125)).
neg(phase_gripper_opening(s126)).
neg(phase_gripper_opening(s128)).
neg(phase_gripper_opening(s129)).
neg(phase_gripper_opening(s130)).
neg(phase_gripper_opening(s131)).
neg(phase_gripper_opening(s132)).
neg(phase_gripper_opening(s133)).
neg(phase_gripper_opening(s134)).
neg(phase_gripper_opening(s135)).
neg(phase_gripper_opening(s136)).
neg(phase_gripper_opening(s137)).
neg(phase_gripper_opening(s138)).
neg(phase_gripper_opening(s139)).
neg(phase_gripper_opening(s140)).
neg(phase_gripper_opening(s141)).
neg(phase_gripper_opening(s142)).
neg(phase_gripper_opening(s143)).
neg(phase_gripper_opening(s144)).
neg(phase_gripper_opening(s145)).
neg(phase_gripper_opening(s146)).
neg(phase_gripper_opening(s147)).
neg(phase_gripper_opening(s148)).
neg(phase_gripper_opening(s149)).
neg(phase_gripper_opening(s150)).
neg(phase_gripper_opening(s151)).
neg(phase_gripper_opening(s152)).
neg(phase_gripper_opening(s153)).
neg(phase_gripper_opening(s154)).
neg(phase_gripper_opening(s155)).
