% Positive examples = pick_delay
% Negative examples = non-pick_delay

pos(phase_pick_delay(s56)).
pos(phase_pick_delay(s57)).
pos(phase_pick_delay(s58)).
pos(phase_pick_delay(s59)).
pos(phase_pick_delay(s60)).
pos(phase_pick_delay(s61)).
pos(phase_pick_delay(s62)).
pos(phase_pick_delay(s63)).
pos(phase_pick_delay(s64)).
pos(phase_pick_delay(s65)).
pos(phase_pick_delay(s66)).
pos(phase_pick_delay(s67)).
pos(phase_pick_delay(s68)).
pos(phase_pick_delay(s69)).

neg(phase_pick_delay(s0)).
neg(phase_pick_delay(s1)).
neg(phase_pick_delay(s2)).
neg(phase_pick_delay(s3)).
neg(phase_pick_delay(s4)).
neg(phase_pick_delay(s6)).
neg(phase_pick_delay(s7)).
neg(phase_pick_delay(s8)).
neg(phase_pick_delay(s9)).
neg(phase_pick_delay(s10)).
neg(phase_pick_delay(s11)).
neg(phase_pick_delay(s12)).
neg(phase_pick_delay(s13)).
neg(phase_pick_delay(s14)).
neg(phase_pick_delay(s15)).
neg(phase_pick_delay(s16)).
neg(phase_pick_delay(s17)).
neg(phase_pick_delay(s18)).
neg(phase_pick_delay(s19)).
neg(phase_pick_delay(s20)).
neg(phase_pick_delay(s21)).
neg(phase_pick_delay(s23)).
neg(phase_pick_delay(s24)).
neg(phase_pick_delay(s25)).
neg(phase_pick_delay(s26)).
neg(phase_pick_delay(s27)).
neg(phase_pick_delay(s28)).
neg(phase_pick_delay(s29)).
neg(phase_pick_delay(s30)).
neg(phase_pick_delay(s31)).
neg(phase_pick_delay(s32)).
neg(phase_pick_delay(s33)).
neg(phase_pick_delay(s34)).
neg(phase_pick_delay(s35)).
neg(phase_pick_delay(s36)).
neg(phase_pick_delay(s37)).
neg(phase_pick_delay(s38)).
neg(phase_pick_delay(s39)).
neg(phase_pick_delay(s40)).
neg(phase_pick_delay(s41)).
neg(phase_pick_delay(s42)).
neg(phase_pick_delay(s43)).
neg(phase_pick_delay(s44)).
neg(phase_pick_delay(s45)).
neg(phase_pick_delay(s46)).
neg(phase_pick_delay(s47)).
neg(phase_pick_delay(s48)).
neg(phase_pick_delay(s49)).
neg(phase_pick_delay(s50)).
neg(phase_pick_delay(s51)).
neg(phase_pick_delay(s52)).
neg(phase_pick_delay(s53)).
neg(phase_pick_delay(s54)).
neg(phase_pick_delay(s71)).
neg(phase_pick_delay(s72)).
neg(phase_pick_delay(s73)).
neg(phase_pick_delay(s74)).
neg(phase_pick_delay(s75)).
neg(phase_pick_delay(s76)).
neg(phase_pick_delay(s77)).
neg(phase_pick_delay(s78)).
neg(phase_pick_delay(s80)).
neg(phase_pick_delay(s81)).
neg(phase_pick_delay(s82)).
neg(phase_pick_delay(s83)).
neg(phase_pick_delay(s84)).
neg(phase_pick_delay(s85)).
neg(phase_pick_delay(s86)).
neg(phase_pick_delay(s87)).
neg(phase_pick_delay(s88)).
neg(phase_pick_delay(s89)).
neg(phase_pick_delay(s90)).
neg(phase_pick_delay(s91)).
neg(phase_pick_delay(s92)).
neg(phase_pick_delay(s94)).
neg(phase_pick_delay(s95)).
neg(phase_pick_delay(s96)).
neg(phase_pick_delay(s97)).
neg(phase_pick_delay(s98)).
neg(phase_pick_delay(s99)).
neg(phase_pick_delay(s100)).
neg(phase_pick_delay(s101)).
neg(phase_pick_delay(s102)).
neg(phase_pick_delay(s103)).
neg(phase_pick_delay(s105)).
neg(phase_pick_delay(s106)).
neg(phase_pick_delay(s107)).
neg(phase_pick_delay(s108)).
neg(phase_pick_delay(s109)).
neg(phase_pick_delay(s110)).
neg(phase_pick_delay(s111)).
neg(phase_pick_delay(s112)).
neg(phase_pick_delay(s113)).
neg(phase_pick_delay(s115)).
neg(phase_pick_delay(s116)).
neg(phase_pick_delay(s117)).
neg(phase_pick_delay(s118)).
neg(phase_pick_delay(s119)).
neg(phase_pick_delay(s120)).
neg(phase_pick_delay(s121)).
neg(phase_pick_delay(s122)).
neg(phase_pick_delay(s123)).
neg(phase_pick_delay(s124)).
neg(phase_pick_delay(s125)).
neg(phase_pick_delay(s126)).
neg(phase_pick_delay(s128)).
neg(phase_pick_delay(s129)).
neg(phase_pick_delay(s130)).
neg(phase_pick_delay(s131)).
neg(phase_pick_delay(s132)).
neg(phase_pick_delay(s133)).
neg(phase_pick_delay(s134)).
neg(phase_pick_delay(s135)).
neg(phase_pick_delay(s136)).
neg(phase_pick_delay(s137)).
neg(phase_pick_delay(s138)).
neg(phase_pick_delay(s139)).
neg(phase_pick_delay(s140)).
neg(phase_pick_delay(s141)).
neg(phase_pick_delay(s142)).
neg(phase_pick_delay(s143)).
neg(phase_pick_delay(s144)).
neg(phase_pick_delay(s145)).
neg(phase_pick_delay(s146)).
neg(phase_pick_delay(s147)).
neg(phase_pick_delay(s148)).
neg(phase_pick_delay(s149)).
neg(phase_pick_delay(s150)).
neg(phase_pick_delay(s151)).
neg(phase_pick_delay(s152)).
neg(phase_pick_delay(s153)).
neg(phase_pick_delay(s154)).
neg(phase_pick_delay(s155)).
