% Positive examples = return_home transitions
% Negative examples = non-return_home transitions

pos(phase_return_home(s128)).
pos(phase_return_home(s129)).
pos(phase_return_home(s130)).
pos(phase_return_home(s131)).
pos(phase_return_home(s132)).
pos(phase_return_home(s133)).
pos(phase_return_home(s134)).
pos(phase_return_home(s135)).
pos(phase_return_home(s136)).
pos(phase_return_home(s137)).
pos(phase_return_home(s138)).
pos(phase_return_home(s139)).
pos(phase_return_home(s140)).
pos(phase_return_home(s141)).
pos(phase_return_home(s142)).
pos(phase_return_home(s143)).
pos(phase_return_home(s144)).
pos(phase_return_home(s145)).
pos(phase_return_home(s146)).
pos(phase_return_home(s147)).
pos(phase_return_home(s148)).
pos(phase_return_home(s149)).
pos(phase_return_home(s150)).
pos(phase_return_home(s151)).
pos(phase_return_home(s152)).
pos(phase_return_home(s153)).
pos(phase_return_home(s154)).
pos(phase_return_home(s155)).

neg(phase_return_home(s0)).
neg(phase_return_home(s1)).
neg(phase_return_home(s2)).
neg(phase_return_home(s3)).
neg(phase_return_home(s4)).
neg(phase_return_home(s6)).
neg(phase_return_home(s7)).
neg(phase_return_home(s8)).
neg(phase_return_home(s9)).
neg(phase_return_home(s10)).
neg(phase_return_home(s11)).
neg(phase_return_home(s12)).
neg(phase_return_home(s13)).
neg(phase_return_home(s14)).
neg(phase_return_home(s15)).
neg(phase_return_home(s16)).
neg(phase_return_home(s17)).
neg(phase_return_home(s18)).
neg(phase_return_home(s19)).
neg(phase_return_home(s20)).
neg(phase_return_home(s21)).
neg(phase_return_home(s23)).
neg(phase_return_home(s24)).
neg(phase_return_home(s25)).
neg(phase_return_home(s26)).
neg(phase_return_home(s27)).
neg(phase_return_home(s28)).
neg(phase_return_home(s29)).
neg(phase_return_home(s30)).
neg(phase_return_home(s31)).
neg(phase_return_home(s32)).
neg(phase_return_home(s33)).
neg(phase_return_home(s34)).
neg(phase_return_home(s35)).
neg(phase_return_home(s36)).
neg(phase_return_home(s37)).
neg(phase_return_home(s38)).
neg(phase_return_home(s39)).
neg(phase_return_home(s40)).
neg(phase_return_home(s41)).
neg(phase_return_home(s42)).
neg(phase_return_home(s43)).
neg(phase_return_home(s44)).
neg(phase_return_home(s45)).
neg(phase_return_home(s46)).
neg(phase_return_home(s47)).
neg(phase_return_home(s48)).
neg(phase_return_home(s49)).
neg(phase_return_home(s50)).
neg(phase_return_home(s51)).
neg(phase_return_home(s52)).
neg(phase_return_home(s53)).
neg(phase_return_home(s54)).
neg(phase_return_home(s56)).
neg(phase_return_home(s57)).
neg(phase_return_home(s58)).
neg(phase_return_home(s59)).
neg(phase_return_home(s60)).
neg(phase_return_home(s61)).
neg(phase_return_home(s62)).
neg(phase_return_home(s63)).
neg(phase_return_home(s64)).
neg(phase_return_home(s65)).
neg(phase_return_home(s66)).
neg(phase_return_home(s67)).
neg(phase_return_home(s68)).
neg(phase_return_home(s69)).
neg(phase_return_home(s71)).
neg(phase_return_home(s72)).
neg(phase_return_home(s73)).
neg(phase_return_home(s74)).
neg(phase_return_home(s75)).
neg(phase_return_home(s76)).
neg(phase_return_home(s77)).
neg(phase_return_home(s78)).
neg(phase_return_home(s80)).
neg(phase_return_home(s81)).
neg(phase_return_home(s82)).
neg(phase_return_home(s83)).
neg(phase_return_home(s84)).
neg(phase_return_home(s85)).
neg(phase_return_home(s86)).
neg(phase_return_home(s87)).
neg(phase_return_home(s88)).
neg(phase_return_home(s89)).
neg(phase_return_home(s90)).
neg(phase_return_home(s91)).
neg(phase_return_home(s92)).
neg(phase_return_home(s94)).
neg(phase_return_home(s95)).
neg(phase_return_home(s96)).
neg(phase_return_home(s97)).
neg(phase_return_home(s98)).
neg(phase_return_home(s99)).
neg(phase_return_home(s100)).
neg(phase_return_home(s101)).
neg(phase_return_home(s102)).
neg(phase_return_home(s103)).
neg(phase_return_home(s105)).
neg(phase_return_home(s106)).
neg(phase_return_home(s107)).
neg(phase_return_home(s108)).
neg(phase_return_home(s109)).
neg(phase_return_home(s110)).
neg(phase_return_home(s111)).
neg(phase_return_home(s112)).
neg(phase_return_home(s113)).
neg(phase_return_home(s115)).
neg(phase_return_home(s116)).
neg(phase_return_home(s117)).
neg(phase_return_home(s118)).
neg(phase_return_home(s119)).
neg(phase_return_home(s120)).
neg(phase_return_home(s121)).
neg(phase_return_home(s122)).
neg(phase_return_home(s123)).
neg(phase_return_home(s124)).
neg(phase_return_home(s125)).
neg(phase_return_home(s126)).
