% Positive examples = retract transitions
% Negative examples = non-retract transitions

pos(phase_retract(s115)).
pos(phase_retract(s116)).
pos(phase_retract(s117)).
pos(phase_retract(s118)).
pos(phase_retract(s119)).
pos(phase_retract(s120)).
pos(phase_retract(s121)).
pos(phase_retract(s122)).
pos(phase_retract(s123)).
pos(phase_retract(s124)).
pos(phase_retract(s125)).
pos(phase_retract(s126)).

neg(phase_retract(s0)).
neg(phase_retract(s1)).
neg(phase_retract(s2)).
neg(phase_retract(s3)).
neg(phase_retract(s4)).
neg(phase_retract(s6)).
neg(phase_retract(s7)).
neg(phase_retract(s8)).
neg(phase_retract(s9)).
neg(phase_retract(s10)).
neg(phase_retract(s11)).
neg(phase_retract(s12)).
neg(phase_retract(s13)).
neg(phase_retract(s14)).
neg(phase_retract(s15)).
neg(phase_retract(s16)).
neg(phase_retract(s17)).
neg(phase_retract(s18)).
neg(phase_retract(s19)).
neg(phase_retract(s20)).
neg(phase_retract(s21)).
neg(phase_retract(s23)).
neg(phase_retract(s24)).
neg(phase_retract(s25)).
neg(phase_retract(s26)).
neg(phase_retract(s27)).
neg(phase_retract(s28)).
neg(phase_retract(s29)).
neg(phase_retract(s30)).
neg(phase_retract(s31)).
neg(phase_retract(s32)).
neg(phase_retract(s33)).
neg(phase_retract(s34)).
neg(phase_retract(s35)).
neg(phase_retract(s36)).
neg(phase_retract(s37)).
neg(phase_retract(s38)).
neg(phase_retract(s39)).
neg(phase_retract(s40)).
neg(phase_retract(s41)).
neg(phase_retract(s42)).
neg(phase_retract(s43)).
neg(phase_retract(s44)).
neg(phase_retract(s45)).
neg(phase_retract(s46)).
neg(phase_retract(s47)).
neg(phase_retract(s48)).
neg(phase_retract(s49)).
neg(phase_retract(s50)).
neg(phase_retract(s51)).
neg(phase_retract(s52)).
neg(phase_retract(s53)).
neg(phase_retract(s54)).
neg(phase_retract(s56)).
neg(phase_retract(s57)).
neg(phase_retract(s58)).
neg(phase_retract(s59)).
neg(phase_retract(s60)).
neg(phase_retract(s61)).
neg(phase_retract(s62)).
neg(phase_retract(s63)).
neg(phase_retract(s64)).
neg(phase_retract(s65)).
neg(phase_retract(s66)).
neg(phase_retract(s67)).
neg(phase_retract(s68)).
neg(phase_retract(s69)).
neg(phase_retract(s71)).
neg(phase_retract(s72)).
neg(phase_retract(s73)).
neg(phase_retract(s74)).
neg(phase_retract(s75)).
neg(phase_retract(s76)).
neg(phase_retract(s77)).
neg(phase_retract(s78)).
neg(phase_retract(s80)).
neg(phase_retract(s81)).
neg(phase_retract(s82)).
neg(phase_retract(s83)).
neg(phase_retract(s84)).
neg(phase_retract(s85)).
neg(phase_retract(s86)).
neg(phase_retract(s87)).
neg(phase_retract(s88)).
neg(phase_retract(s89)).
neg(phase_retract(s90)).
neg(phase_retract(s91)).
neg(phase_retract(s92)).
neg(phase_retract(s94)).
neg(phase_retract(s95)).
neg(phase_retract(s96)).
neg(phase_retract(s97)).
neg(phase_retract(s98)).
neg(phase_retract(s99)).
neg(phase_retract(s100)).
neg(phase_retract(s101)).
neg(phase_retract(s102)).
neg(phase_retract(s103)).
neg(phase_retract(s105)).
neg(phase_retract(s106)).
neg(phase_retract(s107)).
neg(phase_retract(s108)).
neg(phase_retract(s109)).
neg(phase_retract(s110)).
neg(phase_retract(s111)).
neg(phase_retract(s112)).
neg(phase_retract(s113)).
neg(phase_retract(s128)).
neg(phase_retract(s129)).
neg(phase_retract(s130)).
neg(phase_retract(s131)).
neg(phase_retract(s132)).
neg(phase_retract(s133)).
neg(phase_retract(s134)).
neg(phase_retract(s135)).
neg(phase_retract(s136)).
neg(phase_retract(s137)).
neg(phase_retract(s138)).
neg(phase_retract(s139)).
neg(phase_retract(s140)).
neg(phase_retract(s141)).
neg(phase_retract(s142)).
neg(phase_retract(s143)).
neg(phase_retract(s144)).
neg(phase_retract(s145)).
neg(phase_retract(s146)).
neg(phase_retract(s147)).
neg(phase_retract(s148)).
neg(phase_retract(s149)).
neg(phase_retract(s150)).
neg(phase_retract(s151)).
neg(phase_retract(s152)).
neg(phase_retract(s153)).
neg(phase_retract(s154)).
neg(phase_retract(s155)).
