% Positive examples = gripper_closing transitions
% Negative examples = non-gripper_closing transitions

pos(phase_gripper_closing(s71)).
pos(phase_gripper_closing(s72)).
pos(phase_gripper_closing(s73)).
pos(phase_gripper_closing(s74)).
pos(phase_gripper_closing(s75)).
pos(phase_gripper_closing(s76)).
pos(phase_gripper_closing(s77)).
pos(phase_gripper_closing(s78)).

neg(phase_gripper_closing(s0)).
neg(phase_gripper_closing(s1)).
neg(phase_gripper_closing(s2)).
neg(phase_gripper_closing(s3)).
neg(phase_gripper_closing(s4)).
neg(phase_gripper_closing(s6)).
neg(phase_gripper_closing(s7)).
neg(phase_gripper_closing(s8)).
neg(phase_gripper_closing(s9)).
neg(phase_gripper_closing(s10)).
neg(phase_gripper_closing(s11)).
neg(phase_gripper_closing(s12)).
neg(phase_gripper_closing(s13)).
neg(phase_gripper_closing(s14)).
neg(phase_gripper_closing(s15)).
neg(phase_gripper_closing(s16)).
neg(phase_gripper_closing(s17)).
neg(phase_gripper_closing(s18)).
neg(phase_gripper_closing(s19)).
neg(phase_gripper_closing(s20)).
neg(phase_gripper_closing(s21)).
neg(phase_gripper_closing(s23)).
neg(phase_gripper_closing(s24)).
neg(phase_gripper_closing(s25)).
neg(phase_gripper_closing(s26)).
neg(phase_gripper_closing(s27)).
neg(phase_gripper_closing(s28)).
neg(phase_gripper_closing(s29)).
neg(phase_gripper_closing(s30)).
neg(phase_gripper_closing(s31)).
neg(phase_gripper_closing(s32)).
neg(phase_gripper_closing(s33)).
neg(phase_gripper_closing(s34)).
neg(phase_gripper_closing(s35)).
neg(phase_gripper_closing(s36)).
neg(phase_gripper_closing(s37)).
neg(phase_gripper_closing(s38)).
neg(phase_gripper_closing(s39)).
neg(phase_gripper_closing(s40)).
neg(phase_gripper_closing(s41)).
neg(phase_gripper_closing(s42)).
neg(phase_gripper_closing(s43)).
neg(phase_gripper_closing(s44)).
neg(phase_gripper_closing(s45)).
neg(phase_gripper_closing(s46)).
neg(phase_gripper_closing(s47)).
neg(phase_gripper_closing(s48)).
neg(phase_gripper_closing(s49)).
neg(phase_gripper_closing(s50)).
neg(phase_gripper_closing(s51)).
neg(phase_gripper_closing(s52)).
neg(phase_gripper_closing(s53)).
neg(phase_gripper_closing(s54)).
neg(phase_gripper_closing(s56)).
neg(phase_gripper_closing(s57)).
neg(phase_gripper_closing(s58)).
neg(phase_gripper_closing(s59)).
neg(phase_gripper_closing(s60)).
neg(phase_gripper_closing(s61)).
neg(phase_gripper_closing(s62)).
neg(phase_gripper_closing(s63)).
neg(phase_gripper_closing(s64)).
neg(phase_gripper_closing(s65)).
neg(phase_gripper_closing(s66)).
neg(phase_gripper_closing(s67)).
neg(phase_gripper_closing(s68)).
neg(phase_gripper_closing(s69)).
neg(phase_gripper_closing(s80)).
neg(phase_gripper_closing(s81)).
neg(phase_gripper_closing(s82)).
neg(phase_gripper_closing(s83)).
neg(phase_gripper_closing(s84)).
neg(phase_gripper_closing(s85)).
neg(phase_gripper_closing(s86)).
neg(phase_gripper_closing(s87)).
neg(phase_gripper_closing(s88)).
neg(phase_gripper_closing(s89)).
neg(phase_gripper_closing(s90)).
neg(phase_gripper_closing(s91)).
neg(phase_gripper_closing(s92)).
neg(phase_gripper_closing(s94)).
neg(phase_gripper_closing(s95)).
neg(phase_gripper_closing(s96)).
neg(phase_gripper_closing(s97)).
neg(phase_gripper_closing(s98)).
neg(phase_gripper_closing(s99)).
neg(phase_gripper_closing(s100)).
neg(phase_gripper_closing(s101)).
neg(phase_gripper_closing(s102)).
neg(phase_gripper_closing(s103)).
neg(phase_gripper_closing(s105)).
neg(phase_gripper_closing(s106)).
neg(phase_gripper_closing(s107)).
neg(phase_gripper_closing(s108)).
neg(phase_gripper_closing(s109)).
neg(phase_gripper_closing(s110)).
neg(phase_gripper_closing(s111)).
neg(phase_gripper_closing(s112)).
neg(phase_gripper_closing(s113)).
neg(phase_gripper_closing(s115)).
neg(phase_gripper_closing(s116)).
neg(phase_gripper_closing(s117)).
neg(phase_gripper_closing(s118)).
neg(phase_gripper_closing(s119)).
neg(phase_gripper_closing(s120)).
neg(phase_gripper_closing(s121)).
neg(phase_gripper_closing(s122)).
neg(phase_gripper_closing(s123)).
neg(phase_gripper_closing(s124)).
neg(phase_gripper_closing(s125)).
neg(phase_gripper_closing(s126)).
neg(phase_gripper_closing(s128)).
neg(phase_gripper_closing(s129)).
neg(phase_gripper_closing(s130)).
neg(phase_gripper_closing(s131)).
neg(phase_gripper_closing(s132)).
neg(phase_gripper_closing(s133)).
neg(phase_gripper_closing(s134)).
neg(phase_gripper_closing(s135)).
neg(phase_gripper_closing(s136)).
neg(phase_gripper_closing(s137)).
neg(phase_gripper_closing(s138)).
neg(phase_gripper_closing(s139)).
neg(phase_gripper_closing(s140)).
neg(phase_gripper_closing(s141)).
neg(phase_gripper_closing(s142)).
neg(phase_gripper_closing(s143)).
neg(phase_gripper_closing(s144)).
neg(phase_gripper_closing(s145)).
neg(phase_gripper_closing(s146)).
neg(phase_gripper_closing(s147)).
neg(phase_gripper_closing(s148)).
neg(phase_gripper_closing(s149)).
neg(phase_gripper_closing(s150)).
neg(phase_gripper_closing(s151)).
neg(phase_gripper_closing(s152)).
neg(phase_gripper_closing(s153)).
neg(phase_gripper_closing(s154)).
neg(phase_gripper_closing(s155)).
